channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=23.2.1
  - pre-commit=3.5.0
  - python=3.12.0
  - ruff=0.4.8
  - numpy=1.26.4
  - scipy=1.8.0
  - matplotlib=3.6.3
  - scikit-learn=0.23.2
  - seaborn=0.13.2
